// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// fields are actually ordered in the order of priority for implementation
type ChatMessage struct {
	Content                 []byte   `protobuf:"bytes,1,opt,name=Content,json=content,proto3" json:"Content,omitempty"`
	SenderPublicKey         []byte   `protobuf:"bytes,2,opt,name=SenderPublicKey,json=senderPublicKey,proto3" json:"SenderPublicKey,omitempty"`
	SenderProviderPublicKey []byte   `protobuf:"bytes,3,opt,name=SenderProviderPublicKey,json=senderProviderPublicKey,proto3" json:"SenderProviderPublicKey,omitempty"`
	MessageNonce            int64    `protobuf:"varint,4,opt,name=MessageNonce,json=messageNonce,proto3" json:"MessageNonce,omitempty"`
	SenderTimestamp         int64    `protobuf:"varint,5,opt,name=SenderTimestamp,json=senderTimestamp,proto3" json:"SenderTimestamp,omitempty"`
	Signature               []byte   `protobuf:"bytes,6,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ChatMessage) GetSenderPublicKey() []byte {
	if m != nil {
		return m.SenderPublicKey
	}
	return nil
}

func (m *ChatMessage) GetSenderProviderPublicKey() []byte {
	if m != nil {
		return m.SenderProviderPublicKey
	}
	return nil
}

func (m *ChatMessage) GetMessageNonce() int64 {
	if m != nil {
		return m.MessageNonce
	}
	return 0
}

func (m *ChatMessage) GetSenderTimestamp() int64 {
	if m != nil {
		return m.SenderTimestamp
	}
	return 0
}

func (m *ChatMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "message.ChatMessage")
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor_ebceca9e8703e37f) }

var fileDescriptor_ebceca9e8703e37f = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0xd2, 0x77, 0x46, 0x2e, 0x6e, 0xe7, 0x8c, 0xc4, 0x12, 0x5f, 0x08, 0x5f, 0x48, 0x82, 0x8b, 0xdd,
	0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x27, 0x88, 0x3d, 0x19,
	0xc2, 0x15, 0xd2, 0xe0, 0xe2, 0x0f, 0x4e, 0xcd, 0x4b, 0x49, 0x2d, 0x0a, 0x28, 0x4d, 0xca, 0xc9,
	0x4c, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x02, 0xab, 0xe0, 0x2f, 0x46, 0x15, 0x16, 0xb2, 0xe0, 0x12,
	0x87, 0xaa, 0x2c, 0xca, 0x2f, 0xcb, 0x44, 0xd1, 0xc1, 0x0c, 0xd6, 0x21, 0x5e, 0x8c, 0x5d, 0x5a,
	0x48, 0x89, 0x8b, 0x07, 0xea, 0x10, 0xbf, 0xfc, 0xbc, 0xe4, 0x54, 0x09, 0x16, 0x05, 0x46, 0x0d,
	0xe6, 0x20, 0x9e, 0x5c, 0x24, 0x31, 0x84, 0x3b, 0x42, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73,
	0x0b, 0x24, 0x58, 0xc1, 0xca, 0xa0, 0xee, 0x80, 0x0b, 0x0b, 0xc9, 0x70, 0x71, 0x06, 0x67, 0xa6,
	0xe7, 0x25, 0x96, 0x94, 0x16, 0xa5, 0x4a, 0xb0, 0x81, 0x6d, 0xe6, 0x2c, 0x86, 0x09, 0x24, 0xb1,
	0x81, 0x43, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xa3, 0xcc, 0x16, 0x22, 0x01, 0x00,
	0x00,
}
